export const FETCH_PRODUCTS_START = 'admin/FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_OK = 'admin/FETCH_PRODUCTS_OK';
export const FETCH_PRODUCTS_ERROR = 'admin/FETCH_PRODUCTS_ERROR';

export const CREATE_PRODUCT_START = 'admin/CREATE_PRODUCT_START';
export const CREATE_PRODUCT_OK = 'admin/CREATE_PRODUCT_OK';
export const CREATE_PRODUCT_ERROR = 'admin/CREATE_PRODUCT_ERROR';

export const UPDATE_PRODUCT_START = 'admin/UPDATE_PRODUCT_START';
export const UPDATE_PRODUCT_OK = 'admin/UPDATE_PRODUCT_OK';
export const UPDATE_PRODUCT_ERROR = 'admin/UPDATE_PRODUCT_ERROR';

export const REMOVE_PRODUCT_START = 'admin/REMOVE_PRODUCT_START';
export const REMOVE_PRODUCT_OK = 'admin/REMOVE_PRODUCT_OK';
export const REMOVE_PRODUCT_ERROR = 'admin/REMOVE_PRODUCT_ERROR';

export const GET_PRODUCT_START = 'admin/GET_PRODUCT_START';
export const GET_PRODUCT_OK = 'admin/GET_PRODUCT_OK';
export const GET_PRODUCT_ERROR = 'admin/GET_PRODUCT_ERROR';