export const routes = {
    admin: '/admin',
    adminProduct: '/admin/products/:id',
    adminUser: '/admin/user/:id',
    adminUsers: '/admin/users',
    home: '/',
    product: '/products/:id',
    cart: '/cart',
    cartCheckout: '/cart/checkout',
    about: '/about',
    contact: '/contact',
    termsandconditions: '/termsandconditions',
    privacypolicy: '/privacypolicy',
    auth: '/auth',
    authRemember: '/auth/remember',
    authLogin: '/auth/login',
    authRegister: '/auth/register',
}